name: Deploy Backend to Azure App Service (OIDC)

on:
    push:
        branches: [main] # <-- change to your branch if not 'main'
    workflow_dispatch: # <-- manual run button

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read

        env:
            PROJECT: backend/InvoSmart.Api/InvoSmart.Api.csproj
            PUBLISH_DIR: backend/publish
            AZURE_WEBAPP_NAME: invosmart-api-dev

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup .NET 9
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: '9.0.x'

            - name: Restore
              run: dotnet restore $PROJECT

            - name: Build
              run: dotnet build $PROJECT -c Release --no-restore

            - name: Test
              run: |
                  if [ -f "backend/InvoSmart.Tests/InvoSmart.Tests.csproj" ]; then
                    dotnet test backend/InvoSmart.Tests/InvoSmart.Tests.csproj -c Release --no-build
                  else
                    echo "No tests project. Skipping."
                  fi

            - name: Publish
              run: dotnet publish $PROJECT -c Release -o $PUBLISH_DIR /p:UseAppHost=false

            - name: Azure Login (OIDC)
              uses: azure/login@v2
              with:
                  client-id: ${{ secrets.AZURE_CLIENT_ID }}
                  tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                  subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            - name: Deploy to Azure Web App
              uses: azure/webapps-deploy@v3
              with:
                  app-name: ${{ env.AZURE_WEBAPP_NAME }}
                  package: ${{ env.PUBLISH_DIR }}
